# Generated by Django 2.2.4 on 2019-08-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hompeage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('photo1', models.ImageField(blank=True, upload_to='photos')),
                ('photo2', models.ImageField(blank=True, upload_to='photos')),
                ('photo3', models.ImageField(blank=True, upload_to='photos')),
                ('photo4', models.ImageField(blank=True, upload_to='photos')),
                ('photo5', models.ImageField(blank=True, upload_to='photos')),
                ('photo6', models.ImageField(blank=True, upload_to='photos')),
            ],
        ),
    ]
