# Generated by Django 2.2.4 on 2019-08-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('title3', models.CharField(max_length=200)),
                ('title4', models.CharField(max_length=200)),
                ('title5', models.CharField(max_length=200)),
                ('title6', models.CharField(max_length=200)),
                ('description1', models.CharField(max_length=200)),
                ('description2', models.CharField(max_length=200)),
                ('description3', models.CharField(max_length=200)),
                ('description4', models.CharField(max_length=200)),
                ('description5', models.CharField(max_length=200)),
                ('description6', models.CharField(max_length=200)),
                ('photo1', models.ImageField(blank=True, upload_to='photos')),
                ('photo2', models.ImageField(blank=True, upload_to='photos')),
                ('photo3', models.ImageField(blank=True, upload_to='photos')),
                ('photo4', models.ImageField(blank=True, upload_to='photos')),
                ('photo5', models.ImageField(blank=True, upload_to='photos')),
                ('photo6', models.ImageField(blank=True, upload_to='photos')),
            ],
        ),
        migrations.DeleteModel(
            name='Hompeage',
        ),
    ]
